apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskme-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskme-db
  template:
    metadata:
      labels:
        app: taskme-db
    spec:
      containers:
      - name: taskme-db
        image: dvzpoc/taskmedb:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: ""
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
